default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode

development:
  <<: *default
  database: queuebie_development

test:
  <<: *default
  database: queuebie_test

production:
  adapter: postgresql
  encoding: unicode
  database: queuebie_production
  pool: 25
  username: user
